(function(global){
"use strict";
const VERSION="1.0.0-rc.1";
const API_VERSION=1;
function palette(name){return name==='white'?['#ffffff','#f8fafc','#e2e8f0']:name==='silver'?['#ffffff','#dbeafe','#94a3b8']:name==='red'?['#ffffff','#fb7185','#dc2626']:name==='blue'?['#ffffff','#67e8f9','#2563eb']:name==='gold'?['#ffd166','#fff3b0','#ffb703']:name==='club'?['#22ff88','#ff2bd6','#ffffff']:name==='winter'?['#67e8f9','#bfdbfe','#ffffff']:['#ff4d6d','#ffd166','#06d6a0','#4cc9f0','#c77dff'];}
function clamp(v,a,b){return Math.max(a,Math.min(b,Number(v)||0));}
function normalize(input={}){return {count:clamp(input.fireworkCount||8,1,30),density:Math.max(24,clamp(input.fireworkDensity||6,1,10)*14),size:clamp(input.fireworkSize||6,1,10),speed:clamp(input.fireworkSpeed||6,1,10),shape:input.fireworkShape||'random',palette:input.fireworkPalette||'rainbow',smoke:clamp(input.fireworkSmoke||4,0,10),finale:clamp(input.fireworkFinale||4,0,10),rocketType:input.fireworkRocketType||'classic',height:clamp(input.fireworkHeight||7,1,10),wind:clamp(input.fireworkWind||0,-10,10),gravity:clamp(input.fireworkGravity||5,0,10),trail:clamp(input.fireworkTrail||7,0,10),quality:input.quality||'normal'};}
function mountFireworks(host,input={}){
 if(!host) throw new Error('ShowRenderCore: host required');
 const cfg=normalize(input), colors=palette(cfg.palette), rockets=[], sparks=[], smokes=[];
 const canvas=document.createElement('canvas'); canvas.className='fireworksCanvas'; host.appendChild(canvas);
 const ctx=canvas.getContext('2d',{alpha:true}); if(!ctx) throw new Error('ShowRenderCore: canvas unavailable');
 let raf=0,last=0,spawn=999,disposed=false, ro=null;
 function size(){const r=host.getBoundingClientRect();const w=Math.max(320,Math.round(r.width||host.clientWidth||1024));const h=Math.max(180,Math.round(r.height||host.clientHeight||576));const d=Math.min(2,global.devicePixelRatio||1);canvas.width=Math.round(w*d);canvas.height=Math.round(h*d);canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(d,0,0,d,0,0);return {w,h};}
 let dims=size(); if(global.ResizeObserver){ro=new ResizeObserver(()=>{dims=size();});ro.observe(host);} else setTimeout(()=>{dims=size();},0);
 function launch(seed=0){const {w,h}=dims,type=cfg.rocketType,battery=type==='battery';const x=(battery?(15+(seed%8)*10):(10+Math.random()*80))*w/100;const targetY=h*(.10+Math.random()*(.30-cfg.height*.015));const color=colors[(seed+Math.floor(Math.random()*colors.length))%colors.length];rockets.push({x,y:h+8,vx:(Math.random()-.5)*(.35+Math.abs(cfg.wind)*.05),vy:-(5.6+cfg.speed*.4+cfg.height*.22),targetY,color,life:0,type,seed});}
 function shapeAngle(shape,n,total){const t=n/total*Math.PI*2;if(shape==='ring'||shape==='double-ring')return t;if(shape==='heart')return Math.atan2(13*Math.cos(t)-5*Math.cos(2*t)-2*Math.cos(3*t)-Math.cos(4*t),16*Math.sin(t)**3);if(shape==='butterfly')return Math.atan2(Math.sin(t)*(Math.exp(Math.cos(t))-2*Math.cos(4*t)-Math.sin(t/12)**5),Math.cos(t)*(Math.exp(Math.cos(t))-2*Math.cos(4*t)-Math.sin(t/12)**5));if(shape==='smiley')return t;return t;}
 function explode(r){const shape=cfg.shape==='random'?['sphere','ring','palm','chrysanthemum','heart','star','butterfly','willow','double-ring'][Math.floor(Math.random()*9)]:cfg.shape;const total=Math.round(cfg.density*(.75+cfg.size*.12)*(1+cfg.finale*.05));for(let n=0;n<total;n++){let a=shapeAngle(shape,n,total)+(Math.random()-.5)*.08;let sp=(1.4+Math.random()*2.8)*(cfg.size/6);if(shape==='palm')sp*=n%3===0?1.45:.8;if(shape==='willow')sp*=.7+Math.sin(n*.35)*.18;if(shape==='chrysanthemum')sp*=.7+Math.sin(n*.7)*.25;if(shape==='star')sp*=n%2?1.5:.65;if(shape==='double-ring')sp*=n%2?1.45:.72;if(shape==='smiley'){a=n<total*.7?n/(total*.7)*Math.PI*2:(n%2?-.45:.45);sp=n<total*.7?2.4*(cfg.size/6):1.1*(cfg.size/6)}const color=colors[(n+r.seed)%colors.length];sparks.push({x:r.x,y:r.y,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,life:0,max:(shape==='willow'?95:50)+Math.random()*55,color,alpha:1,crackle:Math.random()<cfg.finale*.025});}for(let i=0;i<Math.max(1,cfg.smoke);i++)smokes.push({x:r.x,y:r.y,vx:(Math.random()-.5)*.4,vy:-.15-Math.random()*.25,life:0,max:60+cfg.smoke*10,size:12+Math.random()*30});}
 function frame(t){if(disposed)return;const dt=Math.min(2.2,(t-last||16)/16.67);last=t;const {w,h}=dims;ctx.clearRect(0,0,w,h);spawn+=dt;const rate=Math.max(7,48-cfg.count*1.45-cfg.finale*2.0);if(spawn>rate){spawn=0;launch(Math.floor(t/100));if(cfg.rocketType==='battery'&&Math.random()<.55)launch(Math.floor(t/80)+1);}
 ctx.globalCompositeOperation='source-over';for(const s of smokes){s.life+=dt;s.x+=s.vx*dt;s.y+=s.vy*dt;s.size+=.08*dt;ctx.fillStyle=`rgba(170,175,185,${Math.max(0,.25*(1-s.life/s.max))})`;ctx.beginPath();ctx.arc(s.x,s.y,s.size,0,Math.PI*2);ctx.fill();}
 ctx.globalCompositeOperation='lighter';for(const r of rockets){r.life+=dt;r.vx+=cfg.wind*.002*dt;r.x+=r.vx*dt;r.y+=r.vy*dt;r.vy+=.008*cfg.gravity*dt;const trail=Math.max(8,cfg.trail*3);const g=ctx.createLinearGradient(r.x,r.y,r.x-r.vx*trail,r.y-r.vy*trail);g.addColorStop(0,'#fff');g.addColorStop(.15,r.color);g.addColorStop(1,'transparent');ctx.strokeStyle=g;ctx.lineWidth=r.type==='comet'?4:2;ctx.beginPath();ctx.moveTo(r.x,r.y);ctx.lineTo(r.x-r.vx*trail,r.y-r.vy*trail);ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(r.x,r.y,2.6,0,Math.PI*2);ctx.fill();}
 for(let i=rockets.length-1;i>=0;i--){const r=rockets[i];if(r.y<=r.targetY||r.vy>-1.0){explode(r);rockets.splice(i,1);}}
 for(const p of sparks){p.life+=dt;p.vx+=cfg.wind*.0015*dt;p.vy+=.012*cfg.gravity*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.alpha=Math.max(0,1-p.life/p.max);ctx.globalAlpha=p.alpha;ctx.strokeStyle=p.color;ctx.lineWidth=p.crackle?2.4:1.3;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x-p.vx*3.2,p.y-p.vy*3.2);ctx.stroke();if(p.crackle&&Math.random()<.18){ctx.fillStyle='#fff';ctx.fillRect(p.x-1,p.y-1,2,2);}}
 ctx.globalAlpha=1;for(let i=sparks.length-1;i>=0;i--)if(sparks[i].life>sparks[i].max||sparks[i].y>h+30)sparks.splice(i,1);for(let i=smokes.length-1;i>=0;i--)if(smokes[i].life>smokes[i].max)smokes.splice(i,1);raf=requestAnimationFrame(frame);}
 raf=requestAnimationFrame(frame);
 return {canvas,version:VERSION,apiVersion:API_VERSION,dispose(){disposed=true;cancelAnimationFrame(raf);ro&&ro.disconnect();canvas.remove();},stats(){return {rockets:rockets.length,sparks:sparks.length,smokes:smokes.length,width:dims.w,height:dims.h};}};
}
const api={id:'shared.showrender',name:'ShowRenderCore',version:VERSION,apiVersion:API_VERSION,status:'RELEASE_CANDIDATE',normalize,mountFireworks};
global.ShowRenderCore=Object.freeze(api);
})(window);
